language: csharp
sudo: true
install:
  - sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet
script:
  - cd src/TeamSpeak3QueryApi
  - dotnet restore
  - "dotnet compile -f .NETPlatform,Version=v5.0"
  - "dotnet compile -f DNXCore,Version=v5.0"